### PR TITLE
feat: expo UI and log protocols, remove unused files

### PR DESCRIPTION
**Pull request by Mavr1**

### CODE REVIEW

**Comment by andolojm** [comment]
@jboileau99 i am still getting notifications for this project, heads up you may have some pruning to do. Hope you’re doing well!

**Comment by jboileau99** [comment]
@andolojm Woah! Hope all is well with you too Jeff. Thanks for the heads up 😄

**Comment by jboileau99** [comment]
@andolojm Honestly not sure why you're still getting notifications.. I don't see you as a member of any of the teams added to this repo, nor are you added directly. You're also not listed as a watcher 🤷‍♂️

**Comment by Midnight-Coder** [comment]
@jboileau99 closing this due to inactivity

**Pull request closed without merging**
